// Array de objetos 'shooter'
export const shootersSeed = [
  {
    name: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    birth: '1990-01-01',
    phone: '1234567890',
    country: 'USA',
    city: 'New York',
    address: '123 Main St',
  },
  {
    name: 'Jane',
    lastName: 'Doe',
    email: 'jane.doe@example.com',
    birth: '1991-02-02',
    phone: '0987654321',
    country: 'USA',
    city: 'Los Angeles',
    address: '456 Elm St',
  },
  {
    name: 'Bob',
    lastName: 'Smith',
    email: 'bob.smith@example.com',
    birth: '1992-03-03',
    phone: '1122334455',
    country: 'USA',
    city: 'Chicago',
    address: '789 Oak St',
  },
  {
    name: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    birth: '1993-04-04',
    phone: '6677889900',
    country: 'USA',
    city: 'Houston',
    address: '321 Pine St',
  },
  {
    name: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@example.com',
    birth: '1994-05-05',
    phone: '2244668800',
    country: 'USA',
    city: 'Phoenix',
    address: '654 Maple St',
  },
  {
    name: 'David',
    lastName: 'Davis',
    email: 'david.davis@example.com',
    birth: '1995-06-06',
    phone: '5566778899',
    country: 'USA',
    city: 'Philadelphia',
    address: '987 Cedar St',
  },
  {
    name: 'Emily',
    lastName: 'Evans',
    email: 'emily.evans@example.com',
    birth: '1996-07-07',
    phone: '9988776655',
    country: 'USA',
    city: 'San Antonio',
    address: '345 Birch St',
  },
  {
    name: 'Frank',
    lastName: 'Foster',
    email: 'frank.foster@example.com',
    birth: '1997-08-08',
    phone: '4433221100',
    country: 'USA',
    city: 'San Diego',
    address: '678 Willow St',
  },
  {
    name: 'Grace',
    lastName: 'Green',
    email: 'grace.green@example.com',
    birth: '1998-09-09',
    phone: '7755443322',
    country: 'USA',
    city: 'Dallas',
    address: '210 Spruce St',
  },
  {
    name: 'Harry',
    lastName: 'Hall',
    email: 'harry.hall@example.com',
    birth: '1999-10-10',
    phone: '8899665544',
    country: 'USA',
    city: 'San Jose',
    address: '543 Aspen St',
  },
  {
    name: 'Isabel',
    lastName: 'Ingram',
    email: 'isabel.ingram@example.com',
    birth: '1990-11-11',
    phone: '1122334455',
    country: 'USA',
    city: 'New Orleans',
    address: '789 Magnolia St',
  },
  {
    name: 'James',
    lastName: 'Jones',
    email: 'james.jones@example.com',
    birth: '1991-12-12',
    phone: '9988776655',
    country: 'USA',
    city: 'Cleveland',
    address: '123 Oak St',
  },
  {
    name: 'Kim',
    lastName: 'Keller',
    email: 'kim.keller@example.com',
    birth: '1992-01-01',
    phone: '5544332211',
    country: 'USA',
    city: 'Seattle',
    address: '456 Pine St',
  },
  {
    name: 'Louis',
    lastName: 'Lopez',
    email: 'louis.lopez@example.com',
    birth: '1993-02-02',
    phone: '6677889900',
    country: 'USA',
    city: 'Denver',
    address: '789 Elm St',
  },
  {
    name: 'Mia',
    lastName: 'Martinez',
    email: 'mia.martinez@example.com',
    birth: '1994-03-03',
    phone: '2233445566',
    country: 'USA',
    city: 'Atlanta',
    address: '654 Cedar St',
  },
  {
    name: 'Nathan',
    lastName: 'Nelson',
    email: 'nathan.nelson@example.com',
    birth: '1995-04-04',
    phone: '1122334455',
    country: 'USA',
    city: 'Portland',
    address: '987 Maple St',
  },
  {
    name: 'Olivia',
    lastName: 'Owens',
    email: 'olivia.owens@example.com',
    birth: '1996-05-05',
    phone: '9988776655',
    country: 'USA',
    city: 'Miami',
    address: '345 Birch St',
  },
  {
    name: 'Peter',
    lastName: 'Perez',
    email: 'peter.perez@example.com',
    birth: '1997-06-06',
    phone: '4433221100',
    country: 'USA',
    city: 'Houston',
    address: '678 Oak St',
  },
  {
    name: 'Quinn',
    lastName: 'Quinones',
    email: 'quinn.quinones@example.com',
    birth: '1998-07-07',
    phone: '7755443322',
    country: 'USA',
    city: 'Las Vegas',
    address: '210 Pine St',
  },
  {
    name: 'Riley',
    lastName: 'Rodriguez',
    email: 'riley.rodriguez@example.com',
    birth: '1999-08-08',
    phone: '8899665544',
    country: 'USA',
    city: 'Phoenix',
    address: '543 Maple St',
  },
];

// Array de objetos 'usuario'
export const usersSeed = [
  {
    name: 'Irene',
    lastName: 'Iverson',
    email: 'irene.iverson@example.com',
    birth: '2000-11-11',
    phone: '1123581321',
    country: 'USA',
    city: 'Austin',
    address: '876 Cypress St',
    role: 'admin',
    pass: 'password1',
  },
  {
    name: 'Jack',
    lastName: 'Jackson',
    email: 'jack.jackson@example.com',
    birth: '2001-12-12',
    phone: '3141592653',
    country: 'USA',
    city: 'Jacksonville',
    address: '309 Hickory St',
    role: 'superAdmin',
    pass: 'password2',
  },
  {
    name: 'Karen',
    lastName: 'King',
    email: 'karen.king@example.com',
    birth: '2002-01-01',
    phone: '2718281828',
    country: 'USA',
    city: 'San Francisco',
    address: '492 Walnut St',
    role: 'admin',
    pass: 'password3',
  },
  {
    name: 'Larry',
    lastName: 'Lewis',
    email: 'larry.lewis@example.com',
    birth: '2003-02-02',
    phone: '1618033988',
    country: 'USA',
    city: 'Columbus',
    address: '175 Chestnut St',
    role: 'admin',
    pass: 'password4',
  },
  {
    name: 'Molly',
    lastName: 'Miller',
    email: 'molly.miller@example.com',
    birth: '2004-03-03',
    phone: '1414213562',
    country: 'USA',
    city: 'Fort Worth',
    address: '358 Alder St',
    role: 'admin',
    pass: 'password5',
  },
  {
    name: 'Nathan',
    lastName: 'Nelson',
    email: 'nathan.nelson@example.com',
    birth: '2005-04-04',
    phone: '2233445566',
    country: 'USA',
    city: 'Portland',
    address: '987 Maple St',
    role: 'admin',
    pass: 'password6',
  },
  {
    name: 'Olivia',
    lastName: 'Owens',
    email: 'olivia.owens@example.com',
    birth: '2006-05-05',
    phone: '9988776655',
    country: 'USA',
    city: 'Miami',
    address: '345 Birch St',
    role: 'admin',
    pass: 'password7',
  },
  {
    name: 'Peter',
    lastName: 'Perez',
    email: 'peter.perez@example.com',
    birth: '2007-06-06',
    phone: '4433221100',
    country: 'USA',
    city: 'Houston',
    address: '678 Oak St',
    role: 'admin',
    pass: 'password8',
  },
  {
    name: 'Quinn',
    lastName: 'Quinones',
    email: 'quinn.quinones@example.com',
    birth: '2008-07-07',
    phone: '7755443322',
    country: 'USA',
    city: 'Las Vegas',
    address: '210 Pine St',
    role: 'admin',
    pass: 'password9',
  },
  {
    name: 'Riley',
    lastName: 'Rodriguez',
    email: 'riley.rodriguez@example.com',
    birth: '2009-08-08',
    phone: '8899665544',
    country: 'USA',
    city: 'Phoenix',
    address: '543 Maple St',
    role: 'admin',
    pass: 'password10',
  },
  {
    name: 'Sam',
    lastName: 'Smith',
    email: 'sam.smith@example.com',
    birth: '2010-09-09',
    phone: '1122334455',
    country: 'USA',
    city: 'Dallas',
    address: '789 Cedar St',
    role: 'admin',
    pass: 'password11',
  },
  {
    name: 'Tracy',
    lastName: 'Turner',
    email: 'tracy.turner@example.com',
    birth: '2011-10-10',
    phone: '9988776655',
    country: 'USA',
    city: 'San Francisco',
    address: '123 Birch St',
    role: 'admin',
    pass: 'password12',
  },
  {
    name: 'Ulysses',
    lastName: 'Underwood',
    email: 'ulysses.underwood@example.com',
    birth: '2012-11-11',
    phone: '4433221100',
    country: 'USA',
    city: 'Chicago',
    address: '456 Oak St',
    role: 'admin',
    pass: 'password13',
  },
  {
    name: 'Victoria',
    lastName: 'Vargas',
    email: 'victoria.vargas@example.com',
    birth: '2013-12-12',
    phone: '7755443322',
    country: 'USA',
    city: 'Los Angeles',
    address: '789 Pine St',
    role: 'admin',
    pass: 'password14',
  },
  {
    name: 'William',
    lastName: 'Woods',
    email: 'william.woods@example.com',
    birth: '2014-01-01',
    phone: '1122334455',
    country: 'USA',
    city: 'New York',
    address: '876 Maple St',
    role: 'admin',
    pass: 'password15',
  },
  {
    name: 'Xena',
    lastName: 'Xavier',
    email: 'xena.xavier@example.com',
    birth: '2015-02-02',
    phone: '9988776655',
    country: 'USA',
    city: 'Miami',
    address: '345 Oak St',
    role: 'admin',
    pass: 'password16',
  },
  {
    name: 'Yasmine',
    lastName: 'Young',
    email: 'yasmine.young@example.com',
    birth: '2016-03-03',
    phone: '4433221100',
    country: 'USA',
    city: 'Dallas',
    address: '678 Cedar St',
    role: 'admin',
    pass: 'password17',
  },
  {
    name: 'Zane',
    lastName: 'Zimmerman',
    email: 'zane.zimmerman@example.com',
    birth: '2017-04-04',
    phone: '7755443322',
    country: 'USA',
    city: 'Phoenix',
    address: '210 Birch St',
    role: 'admin',
    pass: 'password18',
  },
  {
    name: 'Ava',
    lastName: 'Anderson',
    email: 'ava.anderson@example.com',
    birth: '2018-05-05',
    phone: '8899665544',
    country: 'USA',
    city: 'San Antonio',
    address: '543 Elm St',
    role: 'admin',
    pass: 'password19',
  },
  {
    name: 'Ben',
    lastName: 'Brown',
    email: 'ben.brown@example.com',
    birth: '2019-06-06',
    phone: '1122334455',
    country: 'USA',
    city: 'Los Angeles',
    address: '789 Pine St',
    role: 'admin',
    pass: 'password20',
  },
];

export const conditionsSeeder = [
  {
    name: 'Operación Encubierta',
    description: 'Infiltración en una base enemiga sin ser detectado',
    mode: true,
    conditionTime: '04:30',
    hits: 0,
    robots: 1,
    shooters: 2,
  },
  {
    name: 'Simulacro de Evacuación',
    description: 'Prueba de evacuación rápida en caso de emergencia',
    mode: true,
    conditionTime: '01:00',
    hits: 1,
    robots: 1,
    shooters: 0,
  },
  {
    name: 'Desafío de Supervivencia',
    description: 'Sobrevivir en un entorno hostil durante 24 horas',
    mode: true,
    conditionTime: '24:00',
    hits: 0,
    robots: 1,
    shooters: 0,
  },
  {
    name: 'Carrera de Robots',
    description: 'Competencia de velocidad entre robots autónomos',
    mode: false,
    conditionTime: '03:30',
    hits: 0,
    robots: 5,
    shooters: 0,
  },
  {
    name: 'Entrenamiento de Tiro al Blanco',
    description: 'Prueba de puntería con pistolas láser',
    mode: true,
    conditionTime: '02:00',
    hits: 2,
    robots: 1,
    shooters: 1,
  },
];
