name: Build Android .apk and make release

on:
  pull_request_target:
    types: [closed]
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Node, Yarn and NPM
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Yarn Install
        run: yarn install

      - name: Bundle React Native code
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Set gradlew permissions
        run: chmod +x ./android/gradlew

      - name: Build application
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Rename the .apk
        run: mv ./android/app/build/outputs/apk/debug/app-debug.apk ./veco_${{ github.event.pull_request.title }}.apk

      # Uploading the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: ./veco_${{ github.event.pull_request.title }}.apk
