name: Add APK to develop-builds branch

on:
  workflow_run:
    workflows: ["Build Android apk"]
    types:
      - completed

jobs:
  add:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request_target' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'develop-builds'

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.workflow_run.pull_requests[0].title }}
          path: .

      - name: Add APK to develop-builds branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add APK from PR ${{ github.event.workflow_run.pull_requests[0].title }}"
          git push
